services:
  eureka_api:
    build: .
    container_name: eureka_api
    restart: always
    network_mode: "host"
    environment:
      PORT: 3050
      DATABASE_URL: postgresql://postgres:vfZlTfp1qCDnVlngOb4FDDJsNKqUgKJb@127.0.0.1:5432/postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
